# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApschedulerJob',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('next_run_time', models.FloatField(blank=True, null=True)),
                ('job_state', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
