# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:15
from __future__ import unicode_literals

import channels.scheduler.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels.scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[channels.scheduler.validators.validate_json_string])),
                ('cron_schedule', models.TextField()),
                ('next_run_time', models.DateTimeField()),
                ('channel_name', models.CharField(max_length=199)),
            ],
            options={
                'ordering': ['-next_run_time'],
            },
        ),
        migrations.DeleteModel(
            name='ApschedulerJob',
        ),
    ]
