# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channels.scheduler', '0002_auto_20170223_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronmessage',
            name='next_run_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
